name: Release

on:
  push:
    tags: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Create Artifacts
      run: cargo build --release --examples --verbose
    - name: Create Archive (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        RUST_TARGET=`rustup show active-toolchain | sed -e 's/[^-]*-\(.*\)\s.*/\1/'`
        tar -C ./target/release/examples/ -zcf nfs-client-${GITHUB_REF_NAME}-${RUST_TARGET}.tar.gz nfs-ls
        echo "RUST_TARGET=${RUST_TARGET}" >> $GITHUB_ENV
        echo "ARTIFACT_PATH=nfs-client-${GITHUB_REF_NAME}-${RUST_TARGET}.tar.gz" >> $GITHUB_ENV
    - name: Create Archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $RUST_TOOLCHAIN = $(rustup show active-toolchain) -Split '[ -]'
        $RUST_ARCH=$RUST_TOOLCHAIN[1]
        $RUST_PLAT=$RUST_TOOLCHAIN[2]
        $RUST_OS=$RUST_TOOLCHAIN[3]
        $RUST_ENV=$RUST_TOOLCHAIN[4]
        $RUST_TARGET="${RUST_ARCH}-${RUST_PLAT}-${RUST_OS}-${RUST_ENV}"
        Compress-Archive -Path 'target\release\examples\nfs-ls.exe' -DestinationPath "nfs-client-${env:GITHUB_REF_NAME}-${RUST_TARGET}.zip"
        Write-Output "RUST_TARGET=$RUST_TARGET" >> $env:GITHUB_ENV
        Write-Output "ARTIFACT_PATH=nfs-client-${env:GITHUB_REF_NAME}-${RUST_TARGET}.zip" >> $env:GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.RUST_TARGET }}
        path: ${{ env.ARTIFACT_PATH }}
        retention-days: 1

  release:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        find ./artifacts -type f
        gh config set prompt disabled
        gh release create ${GITHUB_REF_NAME} ./artifacts/*/*  -t v${GITHUB_REF_NAME} -d
